### ISSUE TITLE
Jsonplaceholder website is down

### ISSUE THREAD

**Issue by quiquesk8** [typicode/jsonplaceholder#163] opened 2021-04-23 14:15 UTC
Hi, when i try to navigate into [https://jsonplaceholder.typicode.com/](url) results in a Heroku page with the following message "There's nothing here, yet." on the page.
Thanks, Quique.

**Comment by snooze92** [comment] 2021-04-23 15:03
Duplicate of https://github.com/typicode/jsonplaceholder/issues/161

**Comment by RitikDua** [comment] 2021-04-24 08:56
It is working right now

**Closed** 2021-04-24 14:28 UTC
